### ISSUE TITLE
Missing modules and files

### ISSUE THREAD

**Issue by coreybruce** [camtaylor/alan#1]
The default source code is missing files and models it need to run in it's default state, I may be doing this wrong but I did want to mention it just in case it is a bug, I modified the source code to stop it looking and loading modules but still no success and can't do must with the missing stuff it needs to do the basic stuff including voice recognition. 

Here is the log of how it all went and sorry if I have butchered it to make it work, I am wanting to learn how this works again if I am doing it incorrectly or I am helping improving this I am that is great.

corey@corey-notebook:~$ '/home/corey/alan-master/passive_listening.sh' 
/home/corey/alan-master/passive_listening.sh: line 2: pocketsphinx_continuous: command not found
python: can't open file 'alan.py': [Errno 2] No such file or directory
corey@corey-notebook:~$ cd /home/corey/alan-master
corey@corey-notebook:~/alan-master$ passive_listening.sh
passive_listening.sh: command not found
corey@corey-notebook:~/alan-master$ sh passive_listening.sh
passive_listening.sh: 2: passive_listening.sh: pocketsphinx_continuous: not found
Traceback (most recent call last):
  File "alan.py", line 2, in <module>
    import nltk
ImportError: No module named nltk
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
bash: /home/corey/alan-master/alan.py: Permission denied
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
Traceback (most recent call last):
  File "/home/corey/alan-master/alan.py", line 2, in <module>
    import nltk
ImportError: No module named nltk
corey@corey-notebook:~/alan-master$ sh passive_listening.sh
passive_listening.sh: 2: passive_listening.sh: pocketsphinx_continuous: not found
passive_listening.sh: 2: passive_listening.sh: /home/corey/alan-master/python: not found
corey@corey-notebook:~/alan-master$ clear
corey@corey-notebook:~/alan-master$ sh passive_listening.sh
passive_listening.sh: 2: passive_listening.sh: pocketsphinx_continuous: not found
passive_listening.sh: 2: passive_listening.sh: /home/corey/alan-master/python: not found
corey@corey-notebook:~/alan-master$ clear
corey@corey-notebook:~/alan-master$ sh passive_listening.sh
passive_listening.sh: 2: passive_listening.sh: pocketsphinx_continuous: not found
passive_listening.sh: 2: passive_listening.sh: /home/corey/alan-master/python: not found
corey@corey-notebook:~/alan-master$ sh passive_listening.sh
passive_listening.sh: 2: passive_listening.sh: pocketsphinx_continuous: not found
passive_listening.sh: 2: passive_listening.sh: /home/corey/alan-master/python: not found
corey@corey-notebook:~/alan-master$ sh passive_listening.sh
passive_listening.sh: 2: passive_listening.sh: pocketsphinx_continuous: not found
passive_listening.sh: 2: passive_listening.sh: alan.py: not found
corey@corey-notebook:~/alan-master$ ^C
corey@corey-notebook:~/alan-master$ clear
corey@corey-notebook:~/alan-master$ sh passive_listening.sh
passive_listening.sh: 2: passive_listening.sh: pocketsphinx_continuous: not found
passive_listening.sh: 2: passive_listening.sh: alan.py: not found
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
Traceback (most recent call last):
  File "/home/corey/alan-master/alan.py", line 2, in <module>
    import nltk
ImportError: No module named nltk
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
Traceback (most recent call last):
  File "/home/corey/alan-master/alan.py", line 5, in <module>
    from language import grammar, vocabulary
  File "/home/corey/alan-master/language/grammar.py", line 1, in <module>
    import nltk
ImportError: No module named nltk
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
Traceback (most recent call last):
  File "/home/corey/alan-master/alan.py", line 4, in <module>
    from language import grammar, vocabulary
  File "/home/corey/alan-master/language/grammar.py", line 1, in <module>
    import nltk
ImportError: No module named nltk
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
Traceback (most recent call last):
  File "/home/corey/alan-master/alan.py", line 5, in <module>
    from language import grammar, vocabulary
  File "/home/corey/alan-master/language/grammar.py", line 2, in <module>
    from wikipage import WikiPage
  File "/home/corey/alan-master/language/wikipage.py", line 3, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
Traceback (most recent call last):
  File "/home/corey/alan-master/alan.py", line 5, in <module>
    from language import grammar, vocabulary
  File "/home/corey/alan-master/language/grammar.py", line 2, in <module>
    from wikipage import WikiPage
  File "/home/corey/alan-master/language/wikipage.py", line 3, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
Traceback (most recent call last):
  File "/home/corey/alan-master/alan.py", line 5, in <module>
    from language import grammar, vocabulary
  File "/home/corey/alan-master/language/grammar.py", line 3, in <module>
    import slang
  File "/home/corey/alan-master/language/slang.py", line 1, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
Traceback (most recent call last):
  File "/home/corey/alan-master/alan.py", line 6, in <module>
    from senses import ears
  File "/home/corey/alan-master/senses/ears.py", line 4, in <module>
    import speech_recognition as sr
ImportError: No module named speech_recognition
corey@corey-notebook:~/alan-master$ '/home/corey/alan-master/alan.py' 
Hello.
sh: 1: festival: not found

> > > hello
> > > global name 'nltk' is not defined
> > > Something went wrong. I can't do that right now.
> > > sh: 1: festival: not found
> > > corey@corey-notebook:~/alan-master$

**Comment by jmelberg** [comment]
You will need to install a few dependencies to get the project to run.
- [NTLK](http://www.nltk.org/install.html):

`pip install -U nltk`
- [PocketSphinx](https://github.com/watsonbox/homebrew-cmu-sphinx) (We used brew)

`brew install cmu-pocketsphinx`
- [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/)

`pip install beautifulsoup4`

We are in the process of putting together an installer. We should have that up soon.

**Thanks for downloading!**

**Comment by coreybruce** [comment]
For the Ubuntu version I am making a script to install everything

The only issue I am having is it is still not finding alan.py when running but running alan.py gives me this error

corey@corey-notebook:~$ '/home/corey/alan-master/alan.py' 
Traceback (most recent call last):
  File "/home/corey/alan-master/alan.py", line 5, in <module>
    from language import grammar, vocabulary
  File "/home/corey/alan-master/language/vocabulary.py", line 8, in <module>
    import memory.store_memories
  File "/home/corey/alan-master/memory/store_memories.py", line 11, in <module>
    conn = sqlite3.connect(sqlite_file)
sqlite3.OperationalError: unable to open database file

is there more dependencies I need?

**Comment by camtaylor** [comment]
It seems that it can't find the database file. Do you see a sqlite file in the memory directory? Also you can try renaming alan-master/ to alan/ because there may be some file path that is hard coded in there.

**Comment by coreybruce** [comment]
No there is no sqlite file in the memory directory, do you have the needed sqlite file it needs? I will also rename the folder to alan to help get it working

**Comment by camtaylor** [comment]
It should automatically create the database file on startup. There is something wrong with the file path I think. Let me know if that works.

**Comment by camtaylor** [comment]
Ok I see an issue. If you run the alan script from outside of the alan directory there will be an error with the path. Try to cd into the alan directory and run the script from there. We will fix this but again this is a very new project  :)

**Comment by coreybruce** [comment]
Ah ok, well were workign through the bugs so this is great

Next error was this, it is to do with it not being able to inport speech_recognition module 

corey@corey-notebook:~$ cd /home/corey/alan
corey@corey-notebook:~/alan$ sh passive_listening.sh
Traceback (most recent call last):
  File "alan.py", line 6, in <module>
    from senses import ears
  File "/home/corey/alan/senses/ears.py", line 4, in <module>
    import speech_recognition as sr
ImportError: No module named speech_recognition

The memories.sqlite file appeared in the memories directory. :)

**Comment by camtaylor** [comment]
Ya I opened a new issue for the sqlite error. So you can get that with pip..

" pip install SpeechRecognition"

**Comment by coreybruce** [comment]
Ok well installed it, were getting close I can feel it, here is the next error

corey@corey-notebook:~/alan$ sh passive_listening.sh
Hello.
sh: 1: festival: not found

> > > EOF when reading a line
> > > Something went wrong. I can't do that right now.
> > > sh: 1: festival: not found

**Comment by camtaylor** [comment]
That is a linux text to speech program...

"sudo apt-get install festival"

**Comment by coreybruce** [comment]
Sorry if I seem a bit ignorant I am kind of new to programming with python and don't know the dependencies needed for alan so I am learning and listing all the dependencies ect in my script I am making to install and set this up. SO I installed festive and he spoke but he still says "Something went wrong. I can't do that right now" and than stops the script.

**Comment by camtaylor** [comment]
No worries man glad to help. When do you get that error? On start up or what?

**Comment by coreybruce** [comment]
Yeah on start up, he will say hello than something when wrong and end the script.

**Comment by camtaylor** [comment]
can you start a hangout chat with thealanbot@gmail.com I will help you out it might be quicker that way.

**Comment by coreybruce** [comment]
sure thing

**Comment by coreybruce** [comment]
Sorry didn't mean to call you, I sent a invite to chat.

**Comment by camtaylor** [comment]
I didn't get it for some reason

**Comment by camtaylor** [comment]
Nevermind

**Comment by coreybruce** [comment]
haha my bad :P
